name: Publish Gatsby

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and publish page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Update Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set GitHub pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
